### PR TITLE
Tasks: Worked on show and added list

### PR DESCRIPTION
**Pull request by daviddavis**
Here's what the new command looks like.

```
$ katello task list --org=ACME
-----------------------------------------------------------------------------------------------------------------------
                                                      Task Status

UUID                                 State     Type                 Start Time          Finish Time         
-----------------------------------------------------------------------------------------------------------------------
aa876462-02a3-44bc-b052-1eda56297482 finished  PulpSyncStatus       2013/05/21 12:00:02 2013/05/21 12:00:04 
4ee985a0-eb4f-4fba-99e2-5717db804c86 finished  content_view_publish 2013/05/21 12:06:53 2013/05/21 12:07:01 
53385826-ec4f-4573-8cdc-02fc47c3a7ef finished  content_view_refresh 2013/05/21 12:10:19 2013/05/21 12:10:30 
92ab8ca3-25a6-4a35-ac54-c17486e805a4 finished  TaskStatus           2013/05/21 12:08:40 2013/05/21 12:09:06 
a7787d52-cc05-4dce-aecc-9b100817c5d0 finished  TaskStatus           2013/05/21 12:07:37 2013/05/21 12:08:04 
d0ef8e73-10f1-4cca-a978-44dfe342e441 finished  TaskStatus           2013/05/21 12:09:11 2013/05/21 12:09:38 
0a0b98a3-3f00-4000-888c-947a6290ab38 timed_out TaskStatus           2013/05/21 12:10:35 2013/05/21 12:11:05 
137a683e-5eba-44a8-ac32-fc45ce4bffe2 finished  content_view_refresh 2013/05/21 12:11:10 2013/05/21 12:11:20 

$ katello task list --org=ACME --state=timed_out
-----------------------------------------------------------------------------------------------------------------------
                                                      Task Status

UUID                                 State     Type                 Start Time          Finish Time         
-----------------------------------------------------------------------------------------------------------------------
0a0b98a3-3f00-4000-888c-947a6290ab38 timed_out TaskStatus           2013/05/21 12:10:35 2013/05/21 12:11:05 

$ katello task list --org=ACME --state=finished --type=content_view_refresh
-----------------------------------------------------------------------------------------------------------------------
                                                      Task Status

UUID                                 State     Type                 Start Time          Finish Time         
-----------------------------------------------------------------------------------------------------------------------
53385826-ec4f-4573-8cdc-02fc47c3a7ef finished  content_view_refresh 2013/05/21 12:10:19 2013/05/21 12:10:30 
137a683e-5eba-44a8-ac32-fc45ce4bffe2 finished  content_view_refresh 2013/05/21 12:11:10 2013/05/21 12:11:20 

$ katello task status --uuid=53385826-ec4f-4573-8cdc-02fc47c3a7ef # pre-existing command
-----------------------------------------------------------------------------------------------------------------------
                                                      Task Status
-----------------------------------------------------------------------------------------------------------------------

UUID        : 53385826-ec4f-4573-8cdc-02fc47c3a7ef
State       : finished
Type        : content_view_refresh
Progress    : None
Start Time  : 2013/05/21 12:10:19
Finish Time : 2013/05/21 12:10:30
Owner ID    : 8
Owner Type  : ContentViewVersion
```

**Note: Do not merge until tests are here.**

### CODE REVIEW

**Comment by ehelms** [comment]
Tests please.

**Comment by omaciel** [comment]
Looks awesome!

**Comment by daviddavis** [comment]
@ehelms for now, I'm hoping for feedback on the commands, opts, etc to make sure it's ok before I add tests.

**Comment by ehelms** [comment]
@daviddavis I know I can read the code to get an idea of these commands, but an example usage of each in the description of the PR might be instructive for those less familiar

**Comment by daviddavis** [comment]
@ehelms, sure. I'll update the description.

**Comment by daviddavis** [comment]
Tests added.

**Comment by komidore64** [comment]
ack

**Pull request merged**
