### PR TITLE
adding find_by_custom_info to python api

### PR DESCRIPTION
**Pull request by jlsherrill**
To support splice reports

### CODE REVIEW

**Comment by komidore64** [comment]
looks good to me ACK

**Comment by xsuchy** [comment]
Is this new function used somewhere? It seems to me as dead code.

**Comment by jlsherrill** [comment]
@xsuchy it was requested by the splice reports team as they work to integrate with katello/headpin.

**Comment by jlsherrill** [comment]
@xsuchy they use the python api portion of the cli directly.

**Comment by xsuchy** [comment]
@jlsherrill ok. It would be nice if this would be stated in commit message (too late) or in inline comment so in future it is not deleted as dead code.

**Comment by thomasmckay** [comment]
@xsuchy I too have switched to using just the API python and not the CLI. How would you determine if code is dead?

**Comment by xsuchy** [comment]
@thomasmckay the purpose of katello-cli is to provide command line utility for katello. If it is used as something else (e.g as API library for python scripts), then it need to be documented. Which of the functions are considered public so we should try to preserve the interface.

**Pull request merged**
