### PR TITLE
org auto-attach - attach available subscriptions to all systems within an organization

### PR DESCRIPTION
**Pull request by komidore64**

### CODE REVIEW

**Comment by iNecas** [comment]
ACK

**Comment by komidore64** [comment]
@beav roger that

**Comment by komidore64** [comment]
@beav boom done

**Comment by omaciel** [comment]
What? No tests??? Booo :-1:

**Comment by komidore64** [comment]
@omaciel boom tests

**Comment by thomasmckay** [comment]
ack

**Pull request merged**
