### PR TITLE
Created rpm and puppet util tests

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by daviddavis** [comment]
@jlsherrill ping

**Comment by omaciel** [comment]
Really glad to see tests for this!

**Comment by jlsherrill** [comment]
@daviddavis see!!! Other people wanted this :+1:

**Comment by jlsherrill** [comment]
APT

**Comment by daviddavis** [comment]
It looks like something weird is going on with pylint. Even [master is failing](https://travis-ci.org/Katello/katello-cli/builds). Will look into it more Monday.

**Pull request merged**
